name: pokemon_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  provider: ^6.1.5+1
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/pokeball1.gif
    - assets/appicon.png

# ✅ App Icon Setup
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appicon.png"

# ✅ Splash Screen Setup
flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: assets/appicon.png

  android_12:
    color: "#FFFFFF"
    image: assets/appicon.png